project_id = "mnuppunshelyjezumqtr"

[functions.create-charge]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.search-products]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false
