project_id = "mnuppunshelyjezumqtr"

[functions.create-charge]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.search-products]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.save-aliexpress-config]
verify_jwt = false

[functions.aliexpress-auth-callback]
verify_jwt = false

[functions.import-products]
verify_jwt = false
