<<<<<<< HEAD
project_id = "mnuppunshelyjezumqtr"
=======
project_id = "mnuppunshelyjezumqtr"

[functions.create-charge]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.search-products]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false
>>>>>>> d29cb800a0e23ebba2ad870c7716bda306c9b698
